# Generated by Django 2.1.8 on 2019-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Code', models.CharField(max_length=50, unique=True)),
                ('Score', models.IntegerField()),
                ('Date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
