# Generated by Django 2.1.8 on 2019-05-21 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.CharField(choices=[('eng', 'Engoneering'), ('hr', 'HR'), ('op', 'Operations')], default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
