# Generated by Django 2.1.8 on 2019-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(choices=[('eng', 'Engineering'), ('hr', 'HR'), ('op', 'Operations')], max_length=6),
        ),
    ]
