# Generated by Django 2.1.8 on 2019-05-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190521_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_Code',
            new_name='employee_code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Score',
            new_name='score',
        ),
    ]
