# Generated by Django 2.1.8 on 2019-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190521_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('D1', 'Engineering'), ('D2', 'HR'), ('D3', 'Operations')], max_length=6),
        ),
    ]
