# Generated by Django 2.1.8 on 2019-05-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190522_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('D1', 'Engineering'), ('D2', 'HR'), ('D3', 'Operations'), ('Waltzz', 'Waltzz')], max_length=6),
        ),
    ]
