# Generated by Django 2.1.8 on 2019-05-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190522_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
